import React from 'react'

export default function PrivacyPolicy() {
    return (
        <div>
<title> Privacy Policy - Digi2L</title>

            <section  className="blog_detail_hero position-relative py-2 mb-5 rocket-lazyload"
            
            style={{backgroundImage: `url("/Digi2limage/Pathbg.svg")` , backgroundRepeat: 'no-repeat',  marginTop: '0px', backgroundSize: 'cover' }} >
        


                    <img src="/Digi2limage/blog_detail1.svg" alt=""

                        style={{ position: 'absolute', right: '0px' ,bottom:'0px'}}
                    />
            
                    <img src="/Digi2limage/blog_detail2.svg" alt=""
                        style={{ position: 'absolute', left: '0px ',top:'0' }} />
                <div className="text-center py-5">
                    <h4 className="poppins-SemiBold lh-base py-4">Privacy Policy</h4>
                </div>
            </section>


            <div className="container">
                <div className="row">
                    <div className="col-md-10 mx-auto mb-4">
                        <p><strong><b>Who are we?</b></strong></p>
                        <p><strong><b>UTC Digital Private Limited</b></strong>, a company having its registered office at, Mumbai, India (“we”, “our” or “us”) take the security of your personal data very seriously and are committed to protecting and respecting the privacy of the users (“you” or your”) of <strong><b>Digi2L</b></strong> Website and App (the “Platform”).</p>
                        <p><strong><b>What is this privacy notice for?</b></strong></p>
                        <p>In conjunction with your use of the Platform, we might handle your personal information. This privacy notice outlines, for the Platform, our data collecting and sharing policies, the purposes for which we use personal data, the safeguards we take to protect it in accordance with data protection regulations, and your privacy rights. It also includes a link to our Terms and Conditions. Please give it a serious read.</p>
                        <p>This Statement applies to Personal Data processed by <strong><b>Digi2L</b></strong> when you:</p>
                        <ul>
                            <li>Visit this website (<a href="">https://digi2l.in/</a>) and/or any other <strong>DIGI2L</strong>website(s) that reference or link to this Statement (collectively, “Website”).</li>
                            <li>Download, use or access any of our numerous internet-based products and services, including appliance platforms, software, or applications, as necessary. (collectively, “Services”).</li>
                            <li>Visit <strong>DIGI2L</strong>’s branded social media sites.</li>
                            <li>Receive correspondence from us, such as emails, phone calls, or other electronic messaging; or data we gather.</li>
                        </ul>
                        <p>We collect some information directly from you (for example, via forms you complete or products or Services you access, download, or otherwise obtain). Such information is generally limited to:</p>
                        <ul>
                            <li>Name, Contact Information, Email Address, IMEI, Device Information,  Product Pick Up Address and Product Code</li>
                            <li>Your correspondence with DIGI2L employees.</li>
                            <li>Material that you post on our social media profiles.</li>
                            <li>Data you submit on the website, such as through online surveys or feedback forms.</li>
                            <li>Data you give when you sign up for Services.</li>
                            <li>Information you give when you set up your account, login information, and details about how you use and prefer the Services.</li>
                            <li>Other information is indirectly obtained from you through the usage of the Services (for example, from observing your actions on the Website or to provision you with account access).</li>
                        </ul>
                        <p><strong><b>Such information is generally limited to:</b></strong></p>
                        <p>Information about how the Services or Website are used is gathered automatically and passively through web logs using a variety of methods, but normally does not specifically identify you or other people. IP addresses, device characteristics, browser kinds, domain names, and other anonymous statistical data about aggregate usage are some examples.</p>
                        <p>Finally, we gather Personal Data from various sources such as public records, publicly available sources or internet sites, vendors, data suppliers and service providers, commercially available marketing lists or registries, telephone directories, social networks (such as LinkedIn), news outlets, and related media. These sources only collect business contact information, such as names, contact information, job titles, IP addresses, and LinkedIn and other social media profiles.</p>
                        <p><strong><b>Use of Personal Data</b></strong></p>
                        <p><strong>DIGI2L </strong>uses your Personal Data when: it is necessary to perform our obligations or exercise our contractual rights; we have a legitimate business interest to process such Personal Data; it is necessary to comply with applicable laws or regulations; we have your consent (where required under applicable law) to use your information<strong> </strong>You have the right to revoke your permission in cases where we rely on it (you may do so by getting in touch with us as described below).).</p>
                        <p><strong><b>The following typical situations are regarded as having such legal justifications:</b></strong></p>
                        <ul>
                            <li><b></b><strong><b>Managing our Website and Offering Services:</b></strong>Personal Data is processed, as necessary, to carry out our contractual responsibilities. In situations where we do not have a contract with you, such processing is supported by our legitimate interest in running and promoting our company, running and managing the website, offering and improving the services, and offering requested material (for example, when you request a quote on our website).</li>
                            <li><b></b><strong><b>User Registration:</b></strong>When you register for an account with DIGI2L, we process your Personal Data as necessary to register and administer your account, provide technical and client support and training, confirm your identity, and send important account and Services information. This processing is done in accordance with our contractual obligations or legitimate interest to provide Services.</li>
                            <li><b></b><strong><b>Support Requests:</b></strong>If you enquire DIGI2L to contact you (for instance, with questions about our products and services), or if you reach out to us using one of the methods listed on our website, we will process your personal data to the extent necessary to carry out your requests and stay in touch with you, or as required by contractual obligations.</li>
                        </ul>
                        <p><strong><b>Compliance; Security and Functionality of Website and Services:</b></strong></p>
                        <p>We process your Personal Data to check compliance with the relevant usage as part of our legitimate interests in assuring compliance with the conditions. In order to fulfil our contractual duties, when applicable, and to provide a safe and useful experience, we may additionally use personal data by measuring how the Website and Services are used. In cases where we have not entered into a contract with you, such processing is derived on our legitimate interest in promoting the security and safety of the Website, Services, systems, and applications as well as in protecting our rights and the rights of others. We reserve the right to monitor, look into, and report any attempts to compromise the security of the Website or Services, to confirm accounts and activity, and to impose our terms and policies.</p>
                        <p><strong>Developing Offerings and Improving Website and Services:</strong></p>
                        <p>To the extent that it is required for our legitimate purpose in enhancing the Website and Services, creating new offers, and providing people with specialised content, we handle your Personal Data in order to evaluate trends, usage, and interactions with the Website and Services and to personalise your experience with our Services. When processing your Personal Data for such development, we may at times directly solicit your opinion. (for instance, by way of survey responses).</p>
                        <p><strong>Marketing Communications; Advertisement:</strong></p>
                        <p>We will use your Personal Data to send you specific marketing materials and other communications only as required to represent such legitimate interests, or, if appropriate, to the degree you have given your prior consent. Promoting our Website and Services, expanding our business, and publicising our offers (whether through direct marketing or providing targeted content adverts) are all in our legitimate business interests.. We may also use your Personal Data to send you tailored advertisements and marketing communications that we believe may be of interest to you</p>
                        <p><strong>Payments:</strong></p>
                        <p>If you have given us with financial information, DIGI2L will use that information to authenticate your identity and collect or process payments as necessary to complete the transaction and meet our contractual responsibilities. obligations to the law For compliance and legal reasons that we deem to be needed by applicable legislation, we may be obligated to process personal data. Our terms of service or other terms and conditions may need to be enforced. Other reasons for which such processing can be necessary include safeguarding our rights to privacy, safety, and property as well as the rights of others. Monitoring the use of the Platform by users</p>
                        <p>To evaluate how you use and interact with the Platform, we employ a variety of tools and gather a variety of data. This data includes information about your visit, such as your IP address, information about your computer systems, device ID, browser details, location, connections, or any data that we may gather through the use of cookies, web beacons/gifts, and behavioural targeting/re-targeting. This information will typically be gathered automatically. Our Cookies Policy contains further details about how we use this kind of technology.</p>
                        <p><strong>Disclosure of your Information</strong></p>
                        <p><strong>DIGI2L may share Personal Data as follows:</strong></p>
                        <ul>
                            <li><strong>Providers of contracted services.</strong>To the extent necessary and in accordance with the legal bases outlined above, we may share Personal Data with contracted service providers, such as companies that handle hosting and system administration, payment processing, analytics, marketing, data enrichment, or client support, as necessary to deliver the Services, run our business operations, or when we think that applicable legislation authorises or requires disclosure. Only the Personal Data required to carry out the services they offer to DIGI2L is given to these service providers. Such service providers are under no circumstances allowed to use the Personal Data they have collected for any other reason than to deliver the specified services to DIGI2L.</li>
                            <li><strong>Your Company: </strong>If you have registered for a DIGI2L offering using your corporate email address and are an authorised user of the Services, we may share Personal Data with your employer to the extent that is necessary to grant you access, to verify accounts and activity, to look into suspicious activity, or to enforce our terms and policies.</li>
                            <li><b></b><strong><b>Mergers or Acquisitions:</b></strong>In the event of a merger, acquisition, consolidation, change of control, corporate divestiture or dissolution where we sell all or a portion of our business or assets, we will disclose necessary Personal Data and such information will be governed by the privacy policies of acquiring entities. In accordance with applicable laws, we will use reasonable efforts to notify you of any transfer of Personal Data to an unaffiliated third party.</li>
                            <li><strong>Data Analytics:</strong>Occasionally, we may share non-personal, anonymized, and statistical data with third parties for the purpose of helping <strong>DIGI2L</strong> with such analysis and improvements. <strong>DIGI2L</strong> may also use anonymous, aggregated utilization data for typical business operations (for example, Governance reporting).</li>
                            <li><strong>Public Forums:</strong>If any part of the Website or <strong>DIGI2L</strong> branded social media sites permit public forum posting, the Personal Data you choose to post, share, upload, or make publicly available may be visible to others. You should never post or share any information that is confidential or about others unless you have permission to do so. We may use the information you provide to personalize your experience and to make content recommendations.</li>
                            <li><b></b><strong><b>Friends/Acquaintances: </b></strong>Please be aware that Digi2L has no control over the actions of your friends or acquaintances regarding the information you share with them. Your shared information may be gathered and utilized by others once it has been published on publicly accessible web pages. Please email us at <a href="/cdn-cgi/l/email-protection#d3b0a6a0a7bcbeb6a1b0b2a1b693b7bab4bae1bffdbabd"><u><span className="__cf_email__" data-cfemail="21425452554e4c4453424053446145484648134d0f484f">[email&#160;protected]</span>, </u></a>if you would like your personal information removed from our blog or community forum. We might occasionally be unable to delete your personal information, in which case we will notify you and explain why. We might also provide you the option to refer a friend to join Digi2L or use our services. For this purpose, if you give us a friend&#8217;s email address, we will utilize that email address.</li>
                        </ul>
                        <p><strong>Using your Data in accordance with Data Protection Law</strong></p>
                        <p>Before we are permitted to use your personal information in the ways outlined in this privacy notice, we must abide by a number of requirements set down by data protection law. Depending on the tasks we are performing, we will rely on one of the following circumstances to use your personal data:</p>
                        <p><strong>Consent</strong></p>
                        <p>We may send you promotional offers for our services or goods if you have given us permission to do so (to the extent that we are required to collect consent under Data Protection Laws). To provide you with information on the service or product you have requested, we may get in touch with you by phone, mail, email, or electronic notifications (where you have consented to those methods of communication). You can get in touch with us as described below at any time to modify your marketing choices.</p>
                        <p><strong>Legitimate interests</strong></p>
                        <p>Your personal data collection serves our legitimate interests because it gives us the knowledge we need to offer you our services and operate our Platform. This requires us to balance your interests as a citizen and your rights under data protection law against our interests in using your personal data (such as providing you with access to the Platform and ensuring that no fraudulent activity is promoted through our platform) (for example, not selling your personal data to third-party marketing companies without your knowledge). The conclusion of this balancing test will determine whether we are permitted to use your personal information in the methods stated in this privacy notice. In carrying out this balancing test, we shall always behave reasonably and with full and proper consideration for your interests.</p>
                        <p>We are permitted to keep and process certain of your personal data in order to offer you the services that you have accepted to receive from us. This is necessary in order to provide you with access to and usage of the platform. We would be unable to give you access to the Platform if you did not furnish us with this personal information.</p>
                        <p><strong>Compliance with a legal obligation</strong></p>
                        <p>We are entitled to process your personal data in order to comply with our legal requirements. We are entitled to treat your personal data for legal claims where it is essential to establish, pursue, or defend a legal claim.</p>
                        <p><strong>Substantial Public Interest</strong></p>
                        <p>On the basis of the Data Protection Act, we are entitled to process your personal data where it is essential for reasons of substantial public interest.</p>
                        <p><strong>Protection Laws</strong></p>
                        <p>If we intend to use your personal data for any other reason not covered by this privacy notice, we will notify you before processing your personal data in this manner.</p>
                        <p><strong>Retention Period</strong></p>
                        <p>Our personal data retention periods are determined by business demands and legal constraints. We keep personal data for as long as it is required for the processing reason(s) for which it was obtained, as well as any other legal, related purpose.</p>
                        <p><strong>We usually keep your information for as long as required to:</strong></p>
                        <ul>
                            <li>answer any questions or objections;</li>
                            <li>to demonstrate that we treated you fairly;</li>
                            <li>to demonstrate that we are meeting our regulatory duties; and/or</li>
                            <li>to keep records in accordance with the requirements that apply to us.</li>
                        </ul>
                        <p>We will also retain your information for as long as it is required by law, regulation, or technology (such as where data has to be held in relation to historic insurance claims). We may preserve it for research or statistical purposes as well. If we do, we will ensure that your privacy is safeguarded and that we only use data for the purposes stated. We shall store data in accordance with your current or potential employer&#8217;s instructions if they have authorized us to treat your personal data on their behalf.</p>
                        <p><strong>Location of Processing</strong></p>
                        <p>Digi2L is completely based in India and operates from there. Furthermore, we host our Services and process your Personal Data entirely in India. However, it is possible that some of the above-mentioned service providers will process Personal Data outside of your jurisdiction, in nations that are not subject to an adequacy decision by your local legislature and/or regulator, and which may not provide the same level of data protection as your jurisdiction. We ensure that the information is protected in accordance with the levels of protection required by applicable legislation, for example, by entering into the requisite back-to-back agreements and, if necessary, standard contractual terms for data transfer as authorised by the EU.</p>
                        <p><strong>Minors</strong></p>
                        <p><strong>DIGI2L</strong>’s Services are solely intended for business clients and are not directed at minors. Transactions on the Platform are only open to those who can make legally binding contracts under the Indian Contract Act of 1872. Persons who are &#8220;incompetent to contract&#8221; under the Indian Contract Act of 1872, such as un-discharged insolvents, are not eligible to use the Platform. If you are a minor, that is, under the age of 18, you may only use the Platform or access content on the Platform with the supervision and prior consent/permission of a parent or legal guardian.</p>
                        <p>We do not collect Personal Information from minors under the age of 18. If you are a parent or legal guardian and you think your kid has given us Personal Data without your permission, please get in touch with us as described below, and we&#8217;ll take the necessary steps to remove the Personal Data from our records.</p>
                        <p><strong>Security of personal information</strong></p>
                        <p>All information you supply to us is hosted on secure servers run by us or our subcontractors, and it is accessed and used in compliance with our security rules and regulations. We limit access to your personal data to employees, affiliates, and third-party service providers who have a legitimate need for it in order to deliver products or services. In order to preserve your personal data located in the nations where we are headquartered from any unauthorised access, we have put in place commercially reasonable physical, electronic, procedural, administrative, and technical precautions in a manner that complies with the security requirements of data protection legislation. However, no security system, no matter how effective, is impregnable. We cannot guarantee the security of these systems or that information submitted by you or on your behalf will not be intercepted while being transmitted over the Internet.</p>
                        <p>In order to meet the best in class standards for Data Privacy and Data Security, we have taken steps to be ISO 27001:2013 complaint. We have taken all reasonable and practical steps to protect your personal information, such as data security for data at rest and data in motion, role-based access, and only working with partners who have implemented the same level of security.</p>
                        <p><strong>How we may contact you</strong></p>
                        <ul>
                            <li><strong>Service communications: </strong>We communicate with you about the Transaction you initiated with us.</li>
                            <li><strong>Marketing communications and editorial newsletters: </strong>With your permission, we may send you materials we believe will be of interest to you, such as Digi2L&#8217;s new offers and updates. This could be via email or SMS, depending on your marketing settings.<br />
                                You may opt out of receiving these emails at any time by clicking on the &#8220;unsubscribe&#8221; or other comparable links contained at the bottom of any emails, or by contacting us at <a href="/cdn-cgi/l/email-protection#64071117100b0901160705160124000d030d56084a0d0a"><u><span className="__cf_email__" data-cfemail="7714020403181a12051416051237131e101e451b591e19">[email&#160;protected]</span></u></a></li>
                            <li><strong>Customer Feedback: </strong>We may contact you from time to time to solicit feedback on your transaction or experience with Digi2L.</li>
                            <li><strong>Responding to your queries or complaints: </strong>If you have contacted us with a question or a complaint, we may contact you to answer your question or handle your complaint.</li>
                        </ul>
                        <p><strong>Rights and Obligations with respect to your Data</strong></p>
                        <p>In relation to the way we process your personal data, you have a variety of rights under data protection regulations. These are listed below. To exercise any of these rights, please contact us using the information below. We will react to any request received from you within one month of receipt.</p>
                        <p>Right 1: The right to access personal information about you that we hold.</p>
                        <p>Right 2: You have the right to request that we correct any inaccurate personal data we have on file for you.</p>
                        <p>Right 3: You have the right to request that we delete any personal information we have on file for you. This right applies only when (for example) we no longer need to use the personal data for the purpose for which it was obtained, or you withdraw your consent (if we are using your personal data based on your consent); or you object to how we use your personal data.</p>
                        <p>Right 4 &#8211; The right to limit our processing of personal data about you. This right applies only if (for example) you dispute the accuracy of the personal data held by us, or if you have the right to require us to erase the personal data but would prefer that our processing be restricted instead; or if we no longer need to use the personal data to achieve the purpose for which it was collected, but you need the data to deal with legal claims.</p>
                        <p>Right 5 &#8211; The right to get your personal data in a structured, generally used, and machine-readable manner. You also have the right to require us to transfer this personal data to another organization at your request.</p>
                        <p>Right 6 &#8211; You have the right to object to the processing of your personal data by us (including for the purposes of sending promotional messages to you).</p>
                        <p>Right 7 &#8211; The right to withdraw your permission where we rely on it to use your personal data (for example, to provide you with promotional messages about our services or products). If you withdraw your consent, we may be unable to offer you some products or services. Certain exceptions apply to these rights in order to protect the public interest (e.g., the prevention or detection of crime) and our interests (e.g. the maintenance of legal privilege).</p>
                        <p><strong>Updating information</strong></p>
                        <p>It is critical to keep your information accurate and up to date. Inaccurate or incomplete information may limit our ability to provide you with relevant services. We shall make reasonable efforts to ensure the accuracy of your personal information. To help us with this, please notify us of any changes to your personal data by updating your profile on the Platform (App) or contacting us as described below. Intentionally supplying false or misleading information, or using another person&#8217;s email address or personal data to get products or services through the Platform, may result in the cancellation of access to the Platform and legal action.</p>
                        <p><strong>Modifications to Privacy Notice</strong></p>
                        <p>We reserve the right to change the Platform&#8217;s content and how we use cookies at any time, therefore this privacy notice, our cookies notice, and any other document to which they relate are subject to modification at any time. If we make significant changes to this privacy notice, we will update the date it was last updated and explicitly mention this in the document. Any modifications we make to this privacy notice take effect immediately after they are posted on the Platform. We urge that you check our privacy notice for changes on a frequent basis. This privacy notice was most recently updated on 03rd February 2023.</p>
                        <p><strong>Questions Regarding this Statement and Your Information</strong></p>
                        <p>Please contact us at if you have any questions or complaints about this Statement or your information at <a href="/cdn-cgi/l/email-protection#90f3e5e3e4fffdf5e2f3f1e2f5d0f4f9f7f9a2fcbef9fe"><u><span className="__cf_email__" data-cfemail="9af9efe9eef5f7ffe8f9fbe8ffdafef3fdf3a8f6b4f3f4">[email&#160;protected]</span></u></a></p>
                        <p><strong>How to complain</strong></p>
                        <p>Please let us know if you are dissatisfied with how we have utilized your personal data or with how we have handled any request you have made regarding your rights. You can reach us using the information provided above. You also have the right to file a complaint with the appropriate supervisory authority after notifying us.</p>
                    </div>
                </div>
            </div>
        </div>
    )
}
