var BaseUrlGlobal = "http://localhost:8000";

export default {
  BaseURL: `${BaseUrlGlobal}/digi2l/assets/images`,
  BlogsGetApi: `${BaseUrlGlobal}/Status/Digi2l/Blogs`,
  FAQGetAPi: `${BaseUrlGlobal}/Status/Digi2l/FAQ`,
  CustomerReviewsGetApi: `${BaseUrlGlobal}/Status/Digi2l/Testimonials`,
  PressGetAPi: `${BaseUrlGlobal}/Status/Digi2l/Press`,
  StoriesGetApi: `${BaseUrlGlobal}/Status/Digi2l/Stories`,
  PartnerGetApi: `${BaseUrlGlobal}/Status/Digi2l/Partner`,
  OpeningsGetApi: `${BaseUrlGlobal}/Status/Digi2l/Openings`,
  LifeSliderGetAPi: `${BaseUrlGlobal}/Status/Digi2l/LifeSlider`,
  HeaderMenuGetApi: `${BaseUrlGlobal}/Status/Digi2l/Header`,
  FooterMenu: `${BaseUrlGlobal}/Status/Digi2l/Footer`,
  BrowserRouteGetApi: `${BaseUrlGlobal}/Status/Digi2l/BrowserRoute`,
  PolicyDetailGetAPi: `${BaseUrlGlobal}/Status/Digi2l/PolicyDetail`,
  OngoingOffersGetAPi: `${BaseUrlGlobal}/Status/Digi2l/OngoingOffers`,
  ServingInGetAPi: `${BaseUrlGlobal}/Status/Digi2l/Servingin`,
  FollowGetIcon: `${BaseUrlGlobal}/Status/Digi2l/Follow`,
  FollowPostIcon: `${BaseUrlGlobal}/Status/Digi2l/Follow/Post`,
  FollowGetHeaderIcon: `${BaseUrlGlobal}/Status/Digi2l/FollowIcon`,
  FollowPostHeaderIcon: `${BaseUrlGlobal}/Status/Digi2l/FollowIcon/Post`,
  FollowGetLogoIcon: `${BaseUrlGlobal}/Status/Digi2l/Logo`,
  GetCounterAPi: `${BaseUrlGlobal}/Status/Digi2l/Counter`,
  GetQuickLinkAPi: `${BaseUrlGlobal}/Status/Digi2l/QuickLink`,
  GetDetailAPi: `${BaseUrlGlobal}/Status/Digi2l/Detail`,
  FooterLogoGetAPi: `${BaseUrlGlobal}/Status/Digi2l/FooterLogo`,
  BrowserRouterApi: `${BaseUrlGlobal}/Status/Digi2l/BrowserRouter`,
  EnquiryPostApi: `${BaseUrlGlobal}/Status/Digi2l/Enquiry/Post`,
};
